# Generated by Django 4.2.24 on 2025-10-15 04:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StripeAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Account display name", max_length=100),
                ),
                (
                    "api_key",
                    models.CharField(help_text="Stripe API key", max_length=200),
                ),
                (
                    "account_id",
                    models.CharField(
                        help_text="Stripe account ID", max_length=100, unique=True
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this account is active"
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "manager",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who manages this Stripe account",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="managed_stripe_accounts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Stripe Account",
                "verbose_name_plural": "Stripe Accounts",
                "db_table": "stripe_accounts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stripe_id",
                    models.CharField(
                        db_index=True,
                        help_text="Stripe transaction ID",
                        max_length=100,
                        unique=True,
                    ),
                ),
                ("amount", models.IntegerField(help_text="Amount in cents")),
                (
                    "fee",
                    models.IntegerField(default=0, help_text="Processing fee in cents"),
                ),
                (
                    "currency",
                    models.CharField(
                        default="usd",
                        help_text="Currency code (usd, eur, etc.)",
                        max_length=3,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("succeeded", "Succeeded"),
                            ("pending", "Pending"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                            ("canceled", "Canceled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("charge", "Charge"),
                            ("refund", "Refund"),
                            ("payout", "Payout"),
                            ("transfer", "Transfer"),
                            ("adjustment", "Adjustment"),
                        ],
                        help_text="Transaction type",
                        max_length=50,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Record creation time",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "stripe_created",
                    models.DateTimeField(help_text="Transaction time from Stripe"),
                ),
                (
                    "customer_email",
                    models.EmailField(blank=True, max_length=100, null=True),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "stripe_metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional metadata from Stripe",
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        help_text="Associated Stripe account",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="stripe_management.stripeaccount",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stripe Transaction",
                "verbose_name_plural": "Stripe Transactions",
                "db_table": "stripe_transactions",
                "ordering": ["-stripe_created"],
                "indexes": [
                    models.Index(
                        fields=["-stripe_created"],
                        name="stripe_tran_stripe__8f719e_idx",
                    ),
                    models.Index(
                        fields=["status"], name="stripe_tran_status_465495_idx"
                    ),
                    models.Index(fields=["type"], name="stripe_tran_type_3c0a27_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="MonthlyStatement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField(help_text="Statement year")),
                ("month", models.IntegerField(help_text="Statement month (1-12)")),
                (
                    "opening_balance",
                    models.IntegerField(
                        default=0, help_text="Opening balance in cents"
                    ),
                ),
                (
                    "closing_balance",
                    models.IntegerField(
                        default=0, help_text="Closing balance in cents"
                    ),
                ),
                (
                    "total_charges",
                    models.IntegerField(default=0, help_text="Total charges in cents"),
                ),
                (
                    "total_refunds",
                    models.IntegerField(default=0, help_text="Total refunds in cents"),
                ),
                (
                    "total_fees",
                    models.IntegerField(default=0, help_text="Total fees in cents"),
                ),
                (
                    "total_payouts",
                    models.IntegerField(default=0, help_text="Total payouts in cents"),
                ),
                (
                    "is_reconciled",
                    models.BooleanField(
                        default=False, help_text="Whether statement is reconciled"
                    ),
                ),
                ("reconciled_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        help_text="Associated Stripe account",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="statements",
                        to="stripe_management.stripeaccount",
                    ),
                ),
                (
                    "reconciled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reconciled_statements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Monthly Statement",
                "verbose_name_plural": "Monthly Statements",
                "db_table": "stripe_monthly_statements",
                "ordering": ["-year", "-month"],
                "indexes": [
                    models.Index(
                        fields=["year", "month"], name="stripe_mont_year_851e2b_idx"
                    ),
                    models.Index(
                        fields=["is_reconciled"], name="stripe_mont_is_reco_73f1d8_idx"
                    ),
                ],
                "unique_together": {("account", "year", "month")},
            },
        ),
    ]
